PTF ingestor
dmitryduev/kowalski pull request #118
Opened 2021-05-06 04:51 UTC by mcoughlin

Script for ingesting PTF files.

2021-05-18 06:33 UTC, dmitryduev requested changes
Thanks a bunch for taking this on, @mcoughlin. 

The ingestion results in the following entry structure:
![image](https://user-images.githubusercontent.com/7557205/118602751-ebc4f480-b767-11eb-9a16-773eb3d7d7c0.png)

Could you please join `ra_data` and `dec_data` into data so that it resembles the structure of the ZTF source data?

Also, all ingested docs have `mag=0` and `magerr=inf` regardless of the flags -- is that a feature or a bug?

2021-05-18 11:25 UTC, mcoughlin commented
ok so I added RA and Dec to the data I think, please check. Could you check with a few more files? I thought this was just a feature of the file you sent, and just looping through the data gives me 0's and inf's.

2021-05-19 21:53 UTC, dmitryduev requested changes
Almost there @mcoughlin :)

2021-05-19 21:53 UTC, dmitryduev commented on tools/ingest_ptf_matchfiles.py
> +                document["dec"] = document["dec"][0]
I suggest to use the median over all available entires instead.

2021-05-19 21:53 UTC, dmitryduev commented on tools/ingest_ptf_matchfiles.py
> +                document["dec"] = document["dec"][0]
I presume this will be an array if there are multiple entries in "data".

2021-05-19 21:53 UTC, dmitryduev commented on tools/ingest_ptf_matchfiles.py
> +                    }
```suggestion
                for t, m, e, f, _ra, _dec in zip(
                    document["mjd"],
                    document["mag"],
                    document["magErr"],
                    document["ipacFlags"],
                    document["ra"],
                    document["dec"],
                ):
                    data_point = {
                        "mjd": t,
                        "mag": m,
                        "magerr": e,
                        "ipacflags": f,
                        "ra": _ra,
                        "dec": _dec,
                    }
```

2021-05-19 21:53 UTC, dmitryduev commented on tools/ingest_ptf_matchfiles.py
> +                                data_point[k] = round(data_point[k], 3)
```suggestion
                            data_point[k] = float(data_point[k])
                            if k == "mjd":
                                data_point[k] = round(data_point[k], 5)
                            elif k not in ("ra", "dec"):
                                data_point[k] = round(data_point[k], 3)
```

2021-05-19 21:53 UTC, dmitryduev commented on tools/ingest_ptf_matchfiles.py
> +                    document["ipacFlags"],
```suggestion
                    document["ipacFlags"],
                    document["ra"],
                    document["dec"],
```

2021-05-19 21:53 UTC, dmitryduev commented on tools/ingest_ptf_matchfiles.py
> +            )
Just drop these, don't need them anymore

2021-05-19 21:55 UTC, mcoughlin commented on tools/ingest_ptf_matchfiles.py
> +                document["dec"] = document["dec"][0]
It is just a single value that looks like a list.

2021-05-19 21:59 UTC, mcoughlin commented on tools/ingest_ptf_matchfiles.py
> +            )
dropped!

2021-05-23 07:26 UTC, dmitryduev approved these changes
Thanks for the quality work @mcoughlin, merging.

2021-05-23 07:26 UTC, merged