WIP: Refactor alert_watcher_ztf
dmitryduev/kowalski pull request #14
Opened 2020-10-17 07:34 UTC by dmitryduev

2020-10-19 23:36 UTC, dannygoldstein commented
Needs tests !

2020-10-20 17:17 UTC, kmshin1397 requested changes
A few minor comments, but looking good! Agree with Danny - we could definitely use more fine-grained tests on Kowalski (i.e. unit tests for each of the three cases for `alert_sentinel_skyportal`). But that may be better put off for another PR (soon though) as I think this one is blocking deployment and we at least have the end-to-end test.

2020-10-20 17:17 UTC, kmshin1397 commented on kowalski/alert_watcher_ztf.py
> +    def alert_post_photometry(self, alert, groups):
Thoughts on renaming this to `alert_put_photometry`? I'm not sure which is better, as `post` keeps it consistent with the other functions like it, but it is technically calling a PUT instead of POST.

2020-10-20 17:17 UTC, kmshin1397 commented on tests/test_ingester.py
> +        # test_filter.remove()
Why are these commented out?

2020-10-20 17:17 UTC, kmshin1397 commented on tests/test_ingester.py
> +                        # }
Why are these commented out?

2020-10-20 17:17 UTC, kmshin1397 commented on kowalski/tns_watcher.py
> +import argparse
Didn't review this as you mentioned, but maybe we should just add a comment at the top of this file to mark it as WIP for now

2020-10-20 17:26 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +                method_whitelist=["HEAD", "GET", "PUT", "POST"]
I'm using `requests.packages.urllib3.util.retry.Retry` and it is still not renamed there as of the latest version.

2020-10-20 17:27 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +                method_whitelist=["HEAD", "GET", "PUT", "POST"]
Added PATCH

2020-10-20 17:30 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +        dflc = pd.concat(
Good point, fixed. "lc" is for "light curve"

2020-10-20 17:32 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +    def alert_post_photometry(self, alert, groups):
sure, renamed

2020-10-20 17:33 UTC, dmitryduev commented on tests/test_ingester.py
> +        # test_filter.remove()
a, oops, was debugging; uncommented back

2020-10-20 17:34 UTC, acrellin requested changes
Just for the sake of making this codebase more accessible to us non-authors in case one of us needs to triage/update at some point, the below requests are all just to aid in readability

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +        a = deepcopy(alert)
```suggestion
        alert = deepcopy(alert)
```
or `new_alert`

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +    a = deepcopy(alert)
full word(s) var name

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +        s = database[clu_version].find(
full word(s) var name

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
>          for m in config['ml_models']:
```suggestion
        for model in config['ml_models']:
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
>                  m_v = config["ml_models"][m]["version"]
```suggestion
                model_version = config["ml_models"][model]["version"]
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
>                  mf = os.path.join(config["path"]["ml_models"], f'{m}_{m_v}.h5')
```suggestion
                model_filepath = os.path.join(config["path"]["ml_models"], f'{model}_{model_version}.h5')
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +                resp = self.api_skyportal("GET", "/api/instrument", {"name": "ZTF"})
```suggestion
                response = self.api_skyportal("GET", "/api/instrument", {"name": "ZTF"})
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +            for ft in active_filters:
```suggestion
            for filter in active_filters:
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +                resp = self.api_skyportal("GET", f"/api/groups/{ft['group_id']}")
```suggestion
                response = self.api_skyportal("GET", f"/api/groups/{ft['group_id']}")
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +            resp = methods[method.lower()](
```suggestion
            response = methods[method.lower()](
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +            resp = methods[method](
```suggestion
            response = methods[method](
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +        resp = self.api_skyportal("POST", f"/api/candidates", alert_thin)
```suggestion
        response = self.api_skyportal("POST", f"/api/candidates", alert_thin)
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +            resp = self.api_skyportal("POST", f"/api/annotation", annotations)
```suggestion
            response = self.api_skyportal("POST", f"/api/annotation", annotations)
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +            resp = self.api_skyportal("POST", f"/api/thumbnail", thumb)
```suggestion
            response = self.api_skyportal("POST", f"/api/thumbnail", thumb)
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +                w = df_photometry.programid == int(pid)
no idea what w means, full word(s) var name please

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +                    resp = self.api_skyportal("PUT", f"/api/photometry", photometry)
```suggestion
                    response = self.api_skyportal("PUT", f"/api/photometry", photometry)
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +        resp = self.api_skyportal("HEAD", f"/api/candidates/{alert['objectId']}")
```suggestion
        response = self.api_skyportal("HEAD", f"/api/candidates/{alert['objectId']}")
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +        resp = self.api_skyportal("HEAD", f"/api/sources/{alert['objectId']}")
```suggestion
        response = self.api_skyportal("HEAD", f"/api/sources/{alert['objectId']}")
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +                    resp = self.api_skyportal("GET", f"/api/candidates/{alert['objectId']}")
```suggestion
                    response = self.api_skyportal("GET", f"/api/candidates/{alert['objectId']}")
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +                resp = self.api_skyportal("GET", f"/api/sources/{alert['objectId']}")
```suggestion
                response = self.api_skyportal("GET", f"/api/sources/{alert['objectId']}")
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/tns_watcher.py
> +    date1_f = date1.strftime('%Y-%m-%d')
```suggestion
    date1_formatted = date1.strftime('%Y-%m-%d')
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/tns_watcher.py
> +    date2_f = date2.strftime('%Y-%m-%d')
```suggestion
    date2_formatted = date2.strftime('%Y-%m-%d')
```

2020-10-20 17:34 UTC, acrellin commented on kowalski/tns_watcher.py
> +    kk = 50 if grab_all else 1
kk? full word(s) var name please

2020-10-20 17:35 UTC, dmitryduev commented on tests/test_ingester.py
> +                        # }
Removed this, it's just a test after all. The story is: I added a real entry in ZTF_alerts_aux to test things out and it took me a while to figure out why a perfectly good candidate was not passing the test filter - that was why, because this explicitly rejects objects with matches with this catalog.

2020-10-20 17:36 UTC, dmitryduev commented on kowalski/tns_watcher.py
> +import argparse
Right, added

2020-10-20 17:49 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +            for ft in active_filters:
Shadows a built-in function ;)

2020-10-20 17:50 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +            for ft in active_filters:
right. you get the idea though. how about `filtr`

2020-10-20 18:02 UTC, kmshin1397 approved these changes

2020-10-20 19:15 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +        a = deepcopy(alert)
Fixed.

2020-10-20 19:15 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +    a = deepcopy(alert)
Fixed.

2020-10-20 19:15 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +        s = database[clu_version].find(
Fixed.

2020-10-20 19:15 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
>          for m in config['ml_models']:
Fixed.

2020-10-20 19:15 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
>                  m_v = config["ml_models"][m]["version"]
Fixed.

2020-10-20 19:15 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
>                  mf = os.path.join(config["path"]["ml_models"], f'{m}_{m_v}.h5')
Fixed.

2020-10-20 19:15 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +                resp = self.api_skyportal("GET", "/api/instrument", {"name": "ZTF"})
Fixed.

2020-10-20 19:15 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +            for ft in active_filters:
Fixed.

2020-10-20 19:15 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +                resp = self.api_skyportal("GET", f"/api/groups/{ft['group_id']}")
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +            resp = methods[method.lower()](
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +            resp = methods[method](
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +        resp = self.api_skyportal("POST", f"/api/candidates", alert_thin)
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +            resp = self.api_skyportal("POST", f"/api/annotation", annotations)
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +            resp = self.api_skyportal("POST", f"/api/thumbnail", thumb)
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +                w = df_photometry.programid == int(pid)
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +                    resp = self.api_skyportal("PUT", f"/api/photometry", photometry)
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +        resp = self.api_skyportal("HEAD", f"/api/candidates/{alert['objectId']}")
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +        resp = self.api_skyportal("HEAD", f"/api/sources/{alert['objectId']}")
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +                    resp = self.api_skyportal("GET", f"/api/candidates/{alert['objectId']}")
Fixed.

2020-10-20 19:16 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +                resp = self.api_skyportal("GET", f"/api/sources/{alert['objectId']}")
Fixed.

2020-10-20 19:17 UTC, dmitryduev commented on kowalski/tns_watcher.py
> +    date1_f = date1.strftime('%Y-%m-%d')
I removed that file for now, it's not ready anyways

2020-10-20 19:27 UTC, acrellin approved these changes

2020-10-20 19:27 UTC, acrellin commented
@dmitryduev thanks for accommodating those requests!

2020-10-20 19:40 UTC, acrellin approved these changes

2020-10-20 19:40 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +        # obj does not exit in SP:
```suggestion
        # obj does not exist in SP:
```

2020-10-20 19:40 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +        if (not is_candidate) and (not is_source):
Could there ever be an `objs` row without a corresponding `sources` or `candidates` row? I thought that you had implemented a HEAD handler for `/api/objs`, but maybe the idea was just floated and never implemented

2020-10-20 19:40 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +        else:
if you add a `return` line in the block above, this `else` could be removed, and the following block could be de-indented (just a minor simplification)

2020-10-20 19:40 UTC, acrellin commented on kowalski/alert_watcher_ztf.py
> +                    log(f"Failed to get source info on {alert['objectId']}")
do you want to `return` here in this case, or should it still continue if this occurs?

2020-10-20 20:00 UTC, dannygoldstein approved these changes

2020-10-20 20:00 UTC, dannygoldstein commented on kowalski/alert_watcher_ztf.py
> +                self.alert_put_photometry(alert, passed_filters)
should be able to  use post here, but this is fine as you probably dont need to track the bulk upload id.

2020-10-20 20:00 UTC, dannygoldstein commented
@dmitryduev LMK when you are ready to merge.

2020-10-20 21:22 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +        log(_err)
actually, there a try/except block that would catch an error here, so removed this for good

2020-10-20 21:37 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +def make_photometry(alert: dict, jd_start: float = None):
Added a bunch of docstrings where those were missing. Alert is a regular ZTF alert, but could be Kowalskified as well, which in this case simply means adding more data to `prv_candidates`

2020-10-20 21:37 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +        df_light_curve['zp'] = 25.0
Removed

2020-10-20 21:38 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +    alert = deepcopy(alert)
Hmm.. 🤔 Must be a remnant of some code where alert would get changed with unintended consequences downstream in the function that called this.

2020-10-20 21:39 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +            .drop_duplicates(subset=["mjd", "magpsf"])
It's intended to be be used on a single `objectId`, so unnecessary.

2020-10-20 21:41 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +        df_light_curve['sigmapsf'] = df_light_curve['sigmapsf'].apply(lambda x: np.float32(x))
Huh, because the stuff that comes in `prv_candidates` can sometimes differ in 1-2 significant digits wrt the stuff that comes in candidates (even though it is the same, or rather should be the same), so just some extra protection.

2020-10-20 21:44 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +            for active_filter in active_filters:
No, it's currently once a day when new listeners are spun up for the night. There's an [open issue](https://github.com/dmitryduev/kowalski/issues/10) on that - I'll implement constant monitoring in a future pr sometime soon.

2020-10-20 21:46 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +                "data": passed_filter.get('data', dict()).get('annotations', dict()),
yes

2020-10-20 21:46 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +    def api_skyportal(self, method: str, endpoint: str, data=None):
added

2020-10-20 21:50 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +    def alert_put_photometry(self, alert, groups):
added

2020-10-20 21:51 UTC, dmitryduev commented on kowalski/alert_watcher_ztf.py
> +                self.alert_put_photometry(alert, passed_filters)
I know, just didn't want to complicate the logic.

2020-10-20 22:21 UTC, merged