Added ZTF crossmatch to PGIR alerts
dmitryduev/kowalski pull request #141
Opened 2021-08-20 06:06 UTC by dekishalay

This PR aims to add ZTF crossmatches (public data only) for all alerts incoming in the PGIR stream. We'd like to set up scanning to include PGIR sources that have ZTF crossmatches. 

Added ZTF_alerts to crossmatch list for PGIR in config.defaults.yaml. Also included filter to include only programid =1.

2021-08-20 06:26 UTC, dmitryduev requested changes
Thanks, @dekishalay. There are two issues with this implementation that I can see: 
- if done this way, the cross-match would suck in and save to `PGIR_alerts_aux` the basic info about potentially many thousands of ZTF alerts, which is a waste of space and likely useless.
- You would get the x-match for only the first time an `objectId` is saved to `PGIR_alerts_aux`, so no new ZTF alert x-matches would propagate there. [This mechanism is meant for static catalogs , and this first-time-save-only mechanism is a deliberate optimization].

Instead, I would recommend implementing a custom filter, in a way similar to how CLU x-match is dealt with, see https://github.com/dmitryduev/kowalski/blob/master/kowalski/alert_broker_pgir.py#L94.
In particular, you may wish to grab only some basic info about the ZTF alerts/objectIds, perhaps only for a limited number of those, or only for the most recent ones -- depending on what will be guiding your decision making when scanning the candidates. If you'd want to run it for every PGIR alert (i.e. not just when an objectId is first encountered by K), the underlying queries have to be efficient.

2021-08-20 06:28 UTC, dmitryduev commented
Also, looks like your pre-commit hook is not working -- linting failed on the CI, please check.

2021-08-20 18:18 UTC, dekishalay commented
Thanks @dmitryduev for the review. I examined the code in alert_broker_pgir.py, and it appears that even the CLU crossmatch is done only once? The external (static) and CLU crossmatches appear to happen inside
       
 if (
            alert_worker.mongo.db[alert_worker.collection_alerts_aux].count_documents(
                {"_id": object_id}, limit=1
            )
            == 0
        ):

which would suggest a one-time crossmatch? Do you suggest adding the ZTF crossmatch outside this if construct?

2021-08-20 23:21 UTC, dmitryduev commented
> Do you suggest adding the ZTF crossmatch outside this if construct?

Yes, exactly. And as you can see, it should be performant since you'd be running it on each and every alert.

2021-08-22 21:03 UTC, dekishalay commented
Hi @dmitryduev, okay I've now added a new function in alert_broker.py to find the most recent ZTF alert (made the function more generic than just for ZTF alerts). Also added adding the ZTF alert to aux in alert_broker_pgir.py

2021-09-03 22:40 UTC, dmitryduev requested changes
Thanks @dekishalay. Please see my comments. 
I think this will need to tested at scale on staging before rolling out to production.

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker.py
> +        Only searches for the most entry to keep it efficient
```suggestion
        Only searches for the most recent entry to keep it efficient
```

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker.py
> +            catalog_filter = {"candidate.programid": {"$eq": 1}}
Why only public data? I am afraid this has to be implemented differently: e.g., grab and store the latest per programid, then filter downstream? Or else, is it true that anyone who has access to PGIR also has access to ZTF programid=3? @doccosmos? That would simplify this by a lot.

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker.py
> +        cone_search_radius_live = 8.0
Why 8"? I would probably make this configurable and move this over to config.

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker.py
> +                "objectId": 1,
```suggestion
                "objectId": 1,
                "candid": 1,
```

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker.py
> +            live_alert = self.mongo.db[live_stream].find_one(
```suggestion
            latest_alert = list(self.mongo.db[live_stream].find(
```

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker.py
> +            catalog_sort = {"candidate.jd": -1}
```suggestion
            catalog_sort = [("candidate.jd", -1)]
```

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker.py
> +                projection={**catalog_projection},
Projection only works with find, find_one return the full doc.

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker.py
> +                sort={**catalog_sort},
```suggestion
                sort=catalog_sort,
                limit=1,
```

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker.py
> +            )
```suggestion
            ))
```

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker.py
> +                xmatches[live_stream] = []
```suggestion
            xmatches[live_stream] = latest_alert if latest_alert else []
```

2021-09-03 22:40 UTC, dmitryduev commented on kowalski/alert_broker_pgir.py
> +                    {"$addToSet": {"ZTF_alerts": {"$each": xmatches_ztf}}},
Did you mean
```suggestion
                    {"$set": {"ZTF_alerts": xmatches_ztf}},
```
? What you have here will add the latest ZTF alert to this list (treating it as a set to avoid duplicates).

2021-09-05 21:09 UTC, dekishalay commented on kowalski/alert_broker.py
> +        cone_search_radius_live = 8.0
8.0" is the typical PSF size for PGIR. Okay to move it to PGIR to enable re-use of the code for other types of cross-matches

2021-09-05 21:11 UTC, dekishalay commented on kowalski/alert_broker.py
> +            catalog_filter = {"candidate.programid": {"$eq": 1}}
The PGIR team includes several members outside ZTF, which is why we want only programid=1 data by default. Only a few members in PGIR have access to programid=3 in ZTF. Why would this programid filter be a problem?

2021-09-05 21:12 UTC, dekishalay commented on kowalski/alert_broker.py
> +                projection={**catalog_projection},
Okay, thanks for the clarification

2021-09-05 21:23 UTC, dekishalay commented on kowalski/alert_broker_pgir.py
> +                    {"$addToSet": {"ZTF_alerts": {"$each": xmatches_ztf}}},
Right, your suggestion looks better since we would avoid adding new alerts from the same ZTF name repeatedly. Okay to include only the latest ZTF alert.

2021-09-08 01:49 UTC, dmitryduev commented
@dekishalay could you please fix linting and commit it?

2021-09-08 05:05 UTC, dekishalay commented
@dmitryduev Merged the base branch and fixed linting for review

2021-09-08 05:30 UTC, dmitryduev requested changes
Thanks @dekishalay, please see my comment. 

I would also like to ask you to test your query out with penquins/Kowalski - this would be more representative than a test on staging. I.e.: iterate over, say 1k PGIR alerts from a night, get their ra/decs, query K with a `cone_search` query from `penquins` with these additional filters and a kwargs.limit=1, and see how long it takes.

2021-09-08 05:30 UTC, dmitryduev commented on kowalski/alert_broker.py
> +    def alert_filter__xmatch_live_stream(
Now that I think about this, your implementation is too PGIR->ZTF specific, so does not belong in the base class (`AlertWorker`), but should go to `PGIRAlertWorker` subclass in `alert_broker_pgir.py`. I would also rename it into ...__xmatch_ztf_alerts and ditch "live_stream" in the func args as your filter, projection, and sort options are very ZTF-specific (like candidate.programid=1).

2021-09-09 05:16 UTC, dekishalay commented on kowalski/alert_broker.py
> +    def alert_filter__xmatch_live_stream(
Thanks @dmitryduev for the suggestion. I've now implemented the change in the next commit.

2021-09-09 06:18 UTC, dekishalay commented
> your

I also ran a test on K to understand how much time it takes to run these crossmatches. Selecting random 1K PGIR alerts from several nights, I ran the same filter and sort on penquins to confirm that the operations take between 1 - 4 seconds, with a median of ~ 2 seconds for 1 K alerts. 

Is this fast enough @dmitryduev ?

2021-09-17 18:16 UTC, dmitryduev approved these changes
A couple last comments and it's good to go in + please rebase off the latest master, that should the failing test.

The index I'm building on the prod db will speed things up a bit, but not dramatically, so should be good enough already:

```JSON
{
  "coordinates.radec_geojson": "2dsphere",
  "candidate.programid": 1,
  "candidate.jd": 1
}
```

2021-09-18 13:35 UTC, dekishalay commented
Thanks @dmitryduev . Committed the suggestions and tests appear to pass. Ready to merge?

2021-09-18 20:19 UTC, dmitryduev commented
Thanks, @dekishalay. Yes, I think it can go in now. The index I was creating is ready so could you please rerun your query timing test once again in the mean time?

2021-09-18 20:20 UTC, merged

2021-09-18 20:59 UTC, dekishalay commented
Thanks! I tried the test again, and it appears to be hovering between 1 and 3 seconds now.