Added custom cutout thumbnail logic for PGIR
dmitryduev/kowalski pull request #142
Opened 2021-09-03 20:23 UTC by dekishalay

This PR modifies the thumbnail generation logic for the specific ZTF and PGIR streams. Separated the thumbnail manipulation logics for ZTF and PGIR.

2021-09-03 22:12 UTC, dmitryduev requested changes
Thanks @dekishalay - please see my suggestions and do check the CI (e.g. on your last commit - https://github.com/dmitryduev/kowalski/pull/142/checks?check_run_id=3509707299).

2021-09-03 22:12 UTC, dmitryduev commented on kowalski/alert_broker.py
> +                    data_corrected = np.rot90(data_flipped_x, 3)
A lot of unnecessary duplication.
```suggestion
        with gzip.open(io.BytesIO(cutout_data), "rb") as f:
            with fits.open(io.BytesIO(f.read()), ignore_missing_simple=True) as hdu:
                image_data = hdu[0].data

        if self.instrument == "ZTF":
            image_data = np.flipud(image_data)
        elif self.instrument == "PGIR":
            image_data = np.rot90(np.fliplr(image_data), 3)
```

2021-09-03 22:12 UTC, dmitryduev commented on kowalski/alert_broker.py
> +        img = np.array(data_corrected)
```suggestion
        img = np.array(image_data)
```

2021-09-03 22:14 UTC, dmitryduev commented
`TNS monitoring` test is expected to fail on a non-master branch, ignore it on the CI.

2021-09-04 04:38 UTC, dekishalay commented on kowalski/alert_broker.py
> +        img = np.array(data_corrected)
This looks fine.

2021-09-04 04:46 UTC, dekishalay commented on kowalski/alert_broker.py
> +                    data_corrected = np.rot90(data_flipped_x, 3)
Looks good!

2021-09-04 06:55 UTC, dmitryduev approved these changes
LGTM! Failure on the CI is expected (need to handle that properly, BTW, but that's on me I guess..), so merging.

2021-09-04 07:00 UTC, merged