Post photometry to skyportal in flux space and handle negative fluxes
dmitryduev/kowalski pull request #21
Opened 2020-10-30 01:40 UTC by dannygoldstein

Requesting review from @profjsb (can't request him as a reviewer formally)

This PR

1. Modifies the `make_photometry` function to convert photometry from magnitude space to flux space. Photometry from negative difference images is given a negative sign in flux space, gracefully handling negative photometry for variable sources and transients with reference image flux. 

2. Modifies the `alert_put_photometry` function to PUT the photometry to skyportal in flux space.

2020-10-30 04:15 UTC, profjsb requested changes

2020-10-30 04:15 UTC, profjsb commented on kowalski/alert_watcher_ztf.py
> +    coeff = df_light_curve['isdiffpos'].apply(lambda x: 1 if x in [True, 1, 'y', 'Y'] else -1)
Yes, Python will handle int*float as we expect but it reads easier that the multiplier is meant to be 1.0 or -1.0
```suggestion
    coeff = df_light_curve['isdiffpos'].apply(lambda x: 1.0 if x in [True, 1, 'y', 'Y'] else -1.0)
```

2020-10-30 04:15 UTC, profjsb commented on kowalski/alert_watcher_ztf.py
> +    df_light_curve['zp'] = 25.
Above you say this is arbitrary but I think the fluxes should be reported in physical units (muJy, eg.) so you need to properly convert `magpsf` using the correct zp. Is this ZP not available?  Regardless, set these values before step 2 and use them as variables thereon

2020-10-30 04:15 UTC, profjsb commented on kowalski/alert_watcher_ztf.py
> +                    "flux": df_photometry.loc[pid_mask, "flux"].tolist(),
How is negative flux handled on the SP side when you need to render mag?

2020-10-30 04:15 UTC, profjsb commented on kowalski/alert_watcher_ztf.py
> +                                              np.log(10) / 2.5
`fluxerr` should be positive-definite, just if `flux` is negative then it will be negative. You need an `abs` I think.

2020-10-30 04:15 UTC, profjsb commented on kowalski/alert_watcher_ztf.py
> +    ) / 5.  # as diffmaglim is the 5-sigma depth
Is this 5-sigma always true for ZTF? What about a different survey (e.g. Gattini)? Seems like it should be configurable.

2020-10-30 04:19 UTC, dannygoldstein commented on kowalski/alert_watcher_ztf.py
> +                    "flux": df_photometry.loc[pid_mask, "flux"].tolist(),
It renders an upper limit.

2020-10-30 04:19 UTC, dannygoldstein commented on kowalski/alert_watcher_ztf.py
> +                                              np.log(10) / 2.5
Ah, good point.

2020-10-30 04:21 UTC, dannygoldstein commented on kowalski/alert_watcher_ztf.py
> +    df_light_curve['zp'] = 25.
@profjsb The ZP is arbitrary in the sense that 

m = -2.5 log(F) + ZP 

where I choose ZP and F is scaled accordingly. On the SP side, the backend will convert this to muJy by rescaling the zp to 23.9 (this is what will produce F in uJy in the ab system).

2020-10-30 04:22 UTC, dannygoldstein commented on kowalski/alert_watcher_ztf.py
> +                                              np.log(10) / 2.5
Fixed.

2020-10-30 04:24 UTC, dannygoldstein commented on kowalski/alert_watcher_ztf.py
> +    ) / 5.  # as diffmaglim is the 5-sigma depth
Yes. This file only handles ZTF, so safe to assume here (Gattini will presumably have an `alert_watcher_gattini.py` or similar).

2020-10-30 04:49 UTC, dannygoldstein commented on kowalski/alert_watcher_ztf.py
> +    df_light_curve['zp'] = 25.
Check out 

http://skyportal.io/docs/api.html#/paths/~1api~1photometry/post

In the `PhotFluxFlexible` schema, both ZP and magsys are required keys. No matter what ZP you post, it will always be converted to uJy on the backend DB.

2020-10-30 04:51 UTC, dannygoldstein commented on kowalski/alert_watcher_ztf.py
> +    df_light_curve['zp'] = 25.
I went ahead and changed zp to 23.9 which renders flux in uJy. However, it wont make a substantive difference, the database representation will be identical either way.

2020-11-20 20:11 UTC, dmitryduev commented
@dannygoldstein terribly sorry, completely forgot about this one! Will revisit after #29 is merged, as the changes here will need to go on top that.

2020-12-02 17:54 UTC, stefanv commented
Now that #29 has been merged, we should get back to this one.

2021-01-16 07:30 UTC, dmitryduev commented
@dannygoldstein I copied your code over to the new `alert_broker_ztf.py` script and filed a PR on your fork https://github.com/dannygoldstein/kowalski/pull/1, please merge.

2021-01-16 07:39 UTC, dmitryduev reviewed
Very sorry it took me soooooooooooooo long to look at your PR, @dannygoldstein! It's LGTM -- I filed a PR on your fork, where I copied your code on top of the new script.

One thing about all this is that we still won't take `magnr` (the reference flux) into account, so the fluxes for variable source will be wrong (also, in those cases you get not only the upper, but also the lower limit, which I think we don't handle on SP). However, looking at the amount of code that would need to be written and executed every time (see [here](https://github.com/dmitryduev/kowalski-archived/blob/7b9582fae6cd37bbd334bca228ef429d96e0e498/kowalski/server.py#L1589) - I wrote it at some point, would have to port it all over) and the fact that forced photometry is coming, I suggest to merge this as is. With FP in place, we won't need to worry about this anymore. Or will we, @doccosmos? 
@dannygoldstein @profjsb your thoughts?

2021-03-15 22:35 UTC, dmitryduev commented
@dannygoldstein do you want to merge the pr on your fork so that we can merge this one?

2021-03-16 00:09 UTC, dannygoldstein commented
I think this should be in good shape now

2021-03-16 01:36 UTC, dmitryduev approved these changes
Awesome, let's merge it in @dannygoldstein! We should prepare for some potential db surgery. I'll deploy this to staging K, will see how it goes tonight.

2021-03-16 01:36 UTC, merged