Update annotations option for alert filters
dmitryduev/kowalski pull request #65
Opened 2021-01-21 07:58 UTC by dmitryduev

This PR Implements optional annotation updating on SP for alerts that have previously passed a user-defined filter in broker mode.

2021-01-21 11:57 UTC, mcoughlin requested changes
Looks really nice. a few small questions.

2021-01-21 11:57 UTC, mcoughlin commented on kowalski/requirements_api.txt
> +aiofiles>=0.6.0
Is there a reason the requirements are no longer being pinned?

2021-01-21 11:57 UTC, mcoughlin commented on kowalski/utils.py
> +            kwargs["timeout"] = self.timeout
Given that the parallelization of this step has been problematic in the past, could an extra statement be added checking like 

try:
    kwargs["timeout"] = self.timeout
except:
    kwargs["timeout"] = DEFAULT_TIMEOUT

2021-01-21 19:12 UTC, dmitryduev commented on kowalski/requirements_api.txt
> +aiofiles>=0.6.0
I dug into this a bit and the source of pip's deps resolver confusion turned out to be tf 2.3.x that for some odd reason required old-ish np. So pinning other stuff that does not depend on np has been an overkill, which is evident from the green checkmark on the CI. With tf 2.4 out, we may loosen the requirements even further, but that needs more testing.

2021-01-21 19:13 UTC, mcoughlin commented on kowalski/requirements_api.txt
> +aiofiles>=0.6.0
Ok makes sense. Just wanted to understand.

2021-01-21 19:16 UTC, dmitryduev commented on kowalski/utils.py
> +            kwargs["timeout"] = self.timeout
Could you explain why this would be needed? I can't recall problems with this particular use case, but I might be forgetting something.

2021-01-21 19:18 UTC, mcoughlin commented on kowalski/utils.py
> +            kwargs["timeout"] = self.timeout
When you parallelize the call with joblib's Parallel, I dont think that their code properly initializes the Class (maybe), and instead just says self.timeout isn't defined. So it would help me if we were sure it was defined.

2021-01-21 19:23 UTC, dmitryduev commented on kowalski/utils.py
> +            kwargs["timeout"] = self.timeout
Ah, that's in `penquins`: https://github.com/dmitryduev/penquins/blob/master/penquins/penquins.py#L40 -- feel free to fix it there.

2021-01-21 19:25 UTC, dmitryduev commented on kowalski/utils.py
> +            kwargs["timeout"] = self.timeout
Fixed it here for you, my friend :)

2021-01-21 19:26 UTC, mcoughlin commented on kowalski/utils.py
> +            kwargs["timeout"] = self.timeout
You such a boss.

2021-01-21 19:26 UTC, mcoughlin approved these changes

2021-01-21 19:29 UTC, dmitryduev commented on kowalski/utils.py
> +            kwargs["timeout"] = self.timeout
@mcoughlin if you accept the invite to penquins, I'll tag you for a review of https://github.com/dmitryduev/penquins/pull/9, too!

2021-01-22 19:36 UTC, kmshin1397 commented on kowalski/alert_broker_ztf.py
> +            if len(annotations["data"]) > 0 and passed_filter.get(
So now, if someone were to set `update_annotation = False` then any new annotations coming for an existing object will just get ignored, right? Is that the behavior we want, instead of the old behavior of overwriting existing annotations? I think it makes sense logically but just wanted to make sure that it won't break anything since we're changing default behavior technically

2021-01-22 20:24 UTC, dmitryduev commented on kowalski/alert_broker_ztf.py
> +            if len(annotations["data"]) > 0 and passed_filter.get(
It's much worse @kmshin1397... Currently this block simply results in errors on the SP side since the POST call we are trying to make now fails due to the origin already/k/v already existing there. This is what has been bloating our Papertrail. Setting `update_annotation = True` will actually trigger overwriting, otherwise the first annotation will be kept with no further attempts to do post anything.

2021-01-22 20:38 UTC, kmshin1397 commented on kowalski/alert_broker_ztf.py
> +            if len(annotations["data"]) > 0 and passed_filter.get(
Ah of course, you're right. I was thinking that just making the post call would overwrite but the erroring makes sense. In that case, yeah this definitely looks good.

2021-01-22 20:38 UTC, kmshin1397 approved these changes

2021-01-22 20:38 UTC, merged