Ingest PS1_STRM Catalog for Phot_z Estimates & Classification
dmitryduev/kowalski pull request #66
Opened 2021-01-21 17:33 UTC by AndyTza

This pull request will ingest to kowalski the phot_z estimates and object classification from the PS1-Source Types and Redshifts with Machine Learning catalog [(PS1-STRM)](https://archive.stsci.edu/hlsp/ps1-strm)

2021-01-21 19:36 UTC, dmitryduev requested changes
Very nice, @AndyTza! Looks like you need to install our pre-commit hook:
```
pip install pre-commit
pre-commit install
```
It'll do the linting for you and the CI will become green.

Otherwise, I think it's ok to get this in. Moving forward, I'm planning to write a general configurable "catalog ingester" with well-defined testing procedures, but that'll take some time.

2021-01-21 20:30 UTC, dmitryduev commented
@AndyTza just updated the developer guidelines, please take a look: https://github.com/dmitryduev/kowalski#developer-guidelines

2021-01-21 22:31 UTC, AndyTza commented
Thank you @dmitryduev 🚀  I ran the ```pip install pre-commit```  and ```pre-commit install``` and it looks like it passed lint now, but now failed at the `test_tns_watcher.py` test

2021-01-22 22:45 UTC, dmitryduev commented
@AndyTza there were several issues with the code, which I committed to your branch (hope you don't mind :)

2021-01-22 22:49 UTC, dmitryduev commented on config.defaults.yaml
> +            _id: 1
```suggestion
            _id: 1
            objID: 1
```

2021-01-22 22:49 UTC, dmitryduev commented on config.defaults.yaml
> +            prob_Star: 1
```suggestion
            prob_Star: 1
            prob_QSO: 1
```

2021-01-24 00:09 UTC, dmitryduev approved these changes

2021-01-24 00:09 UTC, merged