WIP: ZTF triggering api
dmitryduev/kowalski pull request #84
Opened 2021-03-07 23:27 UTC by mcoughlin

Adding API for triggering ZTF.

Partner submission for: skyportal/skyportal#1540

2021-03-07 23:29 UTC, mcoughlin commented
@dmitryduev @kmshin1397 My branch was so far back, I opened a new one and tried your suggestions here. I am very unclear how the OpenAPI stuff as comments like:

              required:
                - queue_name
                - validity_window_mjd
                - targets
                - queue_type
                - user
              properties:
                queue_name:
                  type: string
                validity_window_mjd:
                  type: list
                targets:
                  type: list
                queue_type:
                  type: string
                user:
                  type: string

failed ... internet didn't seem so helpful on this (and seems similar to yours!). Anyways, hopefully this is closer.

2021-03-08 22:45 UTC, dmitryduev requested changes
Very nice @mcoughlin, getting closer!
Do you want to add an API test? Would prob need to mock ZTF's response in some way (see e.g. https://realpython.com/testing-third-party-apis-with-mocks/)

2021-03-08 22:45 UTC, dmitryduev commented on kowalski/api.py
> +        )
Are you ok with `requests`' defaults here? I would at least add a timeout (https://requests.readthedocs.io/en/master/user/advanced/#timeouts).

2021-03-08 22:45 UTC, dmitryduev commented on kowalski/api.py
> +        return web.json_response(dict(r.headers), status=r.status_code)
Please do it as in https://github.com/fritz-marshal/fritz/blob/master/extensions/skyportal/skyportal/handlers/api/kowalski_filter.py#L159 using self.success(...) and self.error(...) inherited from `Handler`.

2021-03-08 22:45 UTC, dmitryduev commented on kowalski/api.py
> +        return web.json_response(dict(r.headers), status=r.status_code)
Same comments as above.

2021-03-08 22:45 UTC, dmitryduev commented on kowalski/requirements_api.txt
> +urllib
The CI erred citing inability to find matching versions of different libs. Could you please relax all the reqs with >='s? (here and in requirements_ingester.txt)

2021-03-08 22:56 UTC, mcoughlin commented on kowalski/requirements_api.txt
> +urllib
I am confused... I just added urllib as a dependency with no >= right? Maybe I misunderstood.

2021-03-08 22:57 UTC, mcoughlin commented on kowalski/api.py
> +                type: object
I just wanted to try something like this:

              required:
                - queue_name
                - validity_window_mjd
                - targets
                - queue_type
                - user
              properties:
                queue_name:
                  type: string
                validity_window_mjd:
                  type: list
                targets:
                  type: list
                queue_type:
                  type: string
                user:
                  type: string

2021-03-08 23:01 UTC, mcoughlin commented on kowalski/api.py
> +                  type: object
Basically 400 passes and 200 does not. What is the appropriate thing here?   

 if "queue_name" not in data:
        msg = f"Error submitting ZTF queue"
        msg += " No queue_name specified"
        logging.error(msg)
        return web.Response(status=400, text=msg)

    if "queue_type" not in data:
        msg = f"Error submitting ZTF queue {data['queue_name']}."
        msg += " No queue_type specified"
        logging.error(msg)
        return web.Response(status=400, text=msg)

    if data["queue_type"] != 'list':
        msg = f"Error submitting ZTF queue {data['queue_name']}."
        msg += " Only list queues are implemented"
        logging.error(msg)
        return web.Response(status=400, text=msg)

    # check if the queue already exists--don't replace it if so
    # (PUT should be idempotent)
    if data['queue_name'] in request.app['scheduler'].queues:
        msg = f"Submitted queue {data['queue_name']} already exists"
        logging.info(msg)
        return web.Response(status=200, text=msg)

2021-03-08 23:09 UTC, dmitryduev commented on kowalski/requirements_api.txt
> +urllib
Right, I'm asking to change it to >= to all libs in here (like supervisor etc.)

2021-03-08 23:10 UTC, dmitryduev commented on kowalski/api.py
> +                  type: object
I'm confused - what's that code?

2021-03-08 23:11 UTC, mcoughlin commented on kowalski/api.py
> +                  type: object
This is the possible set of responses from ZTF (I don't control what comes back from these, as this is just a passthrough interface).

2021-03-08 23:12 UTC, dmitryduev commented on kowalski/api.py
> +                  type: object
Try adding things one by one and seeing when it breaks. Usually it something mis-indented or a list in place of an object or something.

2021-03-12 21:21 UTC, mcoughlin commented
@kmshin1397 could you see what you think of the current version? I don't get this OpenAPI thing at all, but I think I got much of @dmitryduev's other points.

2021-03-15 17:35 UTC, kmshin1397 reviewed
Looking good @mcoughlin! Couple of suggestions from me

2021-03-15 17:35 UTC, kmshin1397 commented on kowalski/api.py
> +    validity_window_mjd: list
Maybe specify list of ints instead of just list?

2021-03-15 17:35 UTC, kmshin1397 commented on kowalski/api.py
> +class ZTFTriggerHandlerTest(Handler):
I see you decided to just go with separate test handlers instead of fighting with the aiohttp mocking. I think that's perfectly  fine, but I wonder if we can't reduce the code duplication here. 

Maybe instead of an entirely new `ZTFTriggerHandlerTest` class, write a constructor to the `ZTFTriggerHandler` class with an optional `test: bool = False` parameter? And then just in the actual handler code have something like `if self.test: return self.success(...)`? It'll probably be easier then to keep the test and real code in sync as well.

2021-03-15 19:10 UTC, mcoughlin commented on kowalski/api.py
> +    validity_window_mjd: list
Ah yeah fixed!

2021-03-15 19:10 UTC, mcoughlin commented on kowalski/api.py
> +class ZTFTriggerHandlerTest(Handler):
Excellent fixed!

2021-03-15 22:34 UTC, dmitryduev approved these changes
Very nice work, thanks for the effort @mcoughlin! Just a few minor requests and this can go in.

2021-03-15 22:34 UTC, dmitryduev commented on kowalski/api.py
> +        # validate and preprocess
just validate?

2021-03-15 22:34 UTC, dmitryduev commented on kowalski/api.py
> +            r = await c.put(url, json=_data, timeout=10)
Let's be "verboser": c -> client_session, r -> response

2021-03-15 22:34 UTC, dmitryduev commented on kowalski/api.py
> +        return self.error(message=f"rejected: {r.content}")
Same here. + "ZTF trigger attempt rejected" or something.

2021-03-15 22:34 UTC, dmitryduev commented on kowalski/api.py
> +        # validate and preprocess
just validate?

2021-03-15 22:34 UTC, dmitryduev commented on kowalski/api.py
> +        return self.error(message=f"rejected: {r.content}")
Same minor comments as above.

2021-03-15 22:34 UTC, dmitryduev commented on kowalski/api.py
> +    ztf_trigger_handler_test = ZTFTriggerHandler(test=True)
Nice @kmshin1397!

2021-03-15 22:34 UTC, dmitryduev commented on kowalski/api.py
> +            web.delete("/api/triggers/ztf.test", ztf_trigger_handler_test.delete),
Is this a standard thing? @kmshin1397 do you know what these should be called in the REST world, is there a best practice/recommended way?

2021-03-15 22:34 UTC, dmitryduev commented on kowalski/api.py
> +            web.delete("/api/triggers/ztf.test", ztf_trigger_handler_test.delete),
I actually like it this way, just checking.

2021-03-15 22:34 UTC, dmitryduev commented on config.defaults.yaml
> +    mountain_ip: "null"
Perhaps just keep this as null so that it would throw as error if undefined in the config?

2021-03-15 22:43 UTC, kmshin1397 commented on kowalski/api.py
> +            web.delete("/api/triggers/ztf.test", ztf_trigger_handler_test.delete),
I don't think it's a standard thing - at least doesn't seem to be standardized though I highly doubt that we're the first to do something like this. Best I can find is that one shouldn't use file extensions i.e. `.xml` which I guess may apply here. We could just rename the routes to `/api/triggers/ztf-test` maybe? But yeah, I do like the general approach and personally would be fine going with this.

2021-03-15 22:46 UTC, mcoughlin commented on kowalski/api.py
> +            r = await c.put(url, json=_data, timeout=10)
Can you help me understand how to do that? I see "->" in def calls.

2021-03-15 23:13 UTC, dmitryduev commented on kowalski/api.py
> +            r = await c.put(url, json=_data, timeout=10)
oh, I just meant renaming your variables for better readability, not type annotations involved lol.

2021-03-15 23:54 UTC, mcoughlin commented on kowalski/api.py
> +            r = await c.put(url, json=_data, timeout=10)
Ah! ok fixed

2021-03-17 01:32 UTC, dmitryduev commented
@kmshin1397 please feel free to merge this in if you're happy with it!

2021-03-17 13:09 UTC, kmshin1397 approved these changes

2021-03-17 13:10 UTC, merged