VLASS ingestion
dmitryduev/kowalski pull request #92
Opened 2021-03-17 01:09 UTC by mcoughlin

This adds a script to enable VLASS ingestion into kowalski.

2021-03-17 19:37 UTC, dmitryduev requested changes
LGTM, just a couple relatively minor requests.

2021-03-17 19:37 UTC, dmitryduev commented on tools/ingest_vlass.py
> +        list(tqdm(pool.imap(process_file, params), total=len(files)))
`pool.imap+tqdm` is broken, please use @kmshin1397's `istarmap` instead, see https://github.com/dmitryduev/kowalski/blob/master/tools/ingest_ztf_source_features.py#L13

2021-03-17 19:37 UTC, dmitryduev commented on tools/ingest_vlass.py
> +    parser = argparse.ArgumentParser()
Could you please scrap all the `argparse` stuff replace it with `python-fire`? (refactor the logic below into a `run()` function and use `fire.Fire(run)`). See https://github.com/dmitryduev/kowalski/blob/master/tools/ingest_ztf_source_features.py for an example.

2021-03-17 19:37 UTC, dmitryduev commented on tools/ingest_vlass.py
> +    # Note CSV data file comes from https://cirada.ca/vlasscatalogueql0
How big are those? Maybe mention the total unpacked size here?

2021-03-17 19:39 UTC, dmitryduev commented
@mcoughlin actually one more request if you don't mind: could you please write a test similar to one in https://github.com/dmitryduev/kowalski/blob/master/tests/test_tools.py#L33? I.e. put a tiny example in /data and test ingestion.

2021-03-17 19:40 UTC, dmitryduev commented on tools/ingest_vlass.py
> +
```suggestion
# init db if necessary
init_db_sync(config=config)
```

2021-03-17 19:41 UTC, dmitryduev commented on tools/ingest_vlass.py
> +    deg2hms,
```suggestion
    deg2hms,
    init_db_sync,
```

2021-03-18 06:51 UTC, dmitryduev approved these changes
Excellente! 🐧

2021-03-18 09:34 UTC, dmitryduev commented on tools/ingest_vlass.py
> +    num_processes: int = mp.cpu_count(),
Noticed that there's only one file, so this should default to 1.

2021-03-18 12:18 UTC, mcoughlin commented on tools/ingest_vlass.py
> +    num_processes: int = mp.cpu_count(),
Yup fixed!

2021-03-18 17:11 UTC, dmitryduev commented
@mcoughlin do you want to x-match the alert stream against VLASS?
btw, I've already ingested the catalog ;)

2021-03-18 17:13 UTC, mcoughlin commented
@dmitryduev My intuition is that this is *most* useful for our light curve work (and in particular the Fermi searches...), but we should definitely discuss within SCoPe.

2021-03-22 20:52 UTC, kmshin1397 approved these changes
Looks good @mcoughlin! Are these VLASS files ever very large? If you foresee needing to ingest a lot more of these at some point, I could imagine we'd be able to speed things up significantly by processing multiple chunks of the `read_csv()` loop at a time with multiprocessing as well as (or instead of) a process per file, especially if you have a small number of very large files. If that's not really a concern then I think this is fine to go in as is :)

2021-03-22 21:08 UTC, mcoughlin commented
@kmshin1397 Thanks! Files are a few GB and tend to go in quickly, but maybe we do that for the next catalog for practice?

2021-03-27 07:32 UTC, merged